name: manter_vivo
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Sinal de Vida
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
          
